# Generated by Django 3.0.6 on 2020-06-01 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication_R01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_Route_Rec', models.CharField(max_length=200)),
                ('route', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Medication R01',
            },
        ),
        migrations.CreateModel(
            name='Medication_R02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_Frequency_Rec', models.CharField(max_length=200)),
                ('frequency', models.CharField(max_length=200)),
                ('abbreviation', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.DO_NOTHING, to='medicalcrud.Medication_R01')),
            ],
            options={
                'verbose_name': 'Medication R02',
            },
        ),
        migrations.CreateModel(
            name='Medication_B00',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_Rec', models.CharField(max_length=200)),
                ('patient_Rec', models.CharField(max_length=200)),
                ('medication_Type', models.CharField(max_length=200)),
                ('medication', models.CharField(max_length=200)),
                ('prescribed_By', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('active_Status', models.BooleanField(default=True)),
                ('medication_Frequency_Rec', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.DO_NOTHING, to='medicalcrud.Medication_R02')),
                ('medication_Route_Rec', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.DO_NOTHING, to='medicalcrud.Medication_R01')),
            ],
            options={
                'verbose_name': 'Medication B00',
            },
        ),
    ]
