# Generated by Django 3.0.6 on 2020-06-01 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalcrud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication_b00',
            old_name='active_Status',
            new_name='active_status',
        ),
        migrations.RenameField(
            model_name='medication_b00',
            old_name='medication_Rec',
            new_name='medication_rec',
        ),
        migrations.RenameField(
            model_name='medication_b00',
            old_name='medication_Type',
            new_name='medication_type',
        ),
        migrations.RenameField(
            model_name='medication_b00',
            old_name='patient_Rec',
            new_name='patient_rec',
        ),
        migrations.RenameField(
            model_name='medication_b00',
            old_name='prescribed_By',
            new_name='prescribed_by',
        ),
        migrations.RenameField(
            model_name='medication_r01',
            old_name='medication_Route_Rec',
            new_name='medication_route_rec',
        ),
        migrations.RenameField(
            model_name='medication_r02',
            old_name='medication_Frequency_Rec',
            new_name='medication_frequency_rec',
        ),
        migrations.RemoveField(
            model_name='medication_b00',
            name='medication_Frequency_Rec',
        ),
        migrations.RemoveField(
            model_name='medication_b00',
            name='medication_Route_Rec',
        ),
        migrations.AddField(
            model_name='medication_b00',
            name='medication_frequency_rec',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalcrud.Medication_R02'),
        ),
        migrations.AddField(
            model_name='medication_b00',
            name='medication_route_rec',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalcrud.Medication_R01'),
        ),
        migrations.AlterField(
            model_name='medication_r02',
            name='abbreviation',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalcrud.Medication_R01'),
        ),
    ]
